/*
 * Enode API
 *
 * The Enode API is designed to make smart charging applications easy to develop. We provide an abstraction layer that reduces the complexity when extracting vehicle data and sending commands to vehicles from a variety of manufacturers.  The API has a RESTful architecture and utilizes OAuth2 authorization. 
 *
 * The version of the OpenAPI document: 1.17.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EnodeApi.Client.OpenAPIDateConverter;

namespace EnodeApi.Model
{
    /// <summary>
    /// A collection of descriptors that describe the capabilities of this specific charger
    /// </summary>
    [DataContract(Name = "ChargerCapabilities")]
    public partial class ChargerCapabilities : IEquatable<ChargerCapabilities>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChargerCapabilities" /> class.
        /// </summary>
        /// <param name="information">information.</param>
        /// <param name="chargeState">chargeState.</param>
        /// <param name="startCharging">startCharging.</param>
        /// <param name="stopCharging">stopCharging.</param>
        /// <param name="setMaxCurrent">setMaxCurrent.</param>
        public ChargerCapabilities(ChargerCapabilitiesInformation information = default(ChargerCapabilitiesInformation), ChargerCapabilitiesChargeState chargeState = default(ChargerCapabilitiesChargeState), ChargerCapabilitiesStartCharging startCharging = default(ChargerCapabilitiesStartCharging), ChargerCapabilitiesStopCharging stopCharging = default(ChargerCapabilitiesStopCharging), ChargerCapabilitiesSetMaxCurrent setMaxCurrent = default(ChargerCapabilitiesSetMaxCurrent))
        {
            this.Information = information;
            this.ChargeState = chargeState;
            this.StartCharging = startCharging;
            this.StopCharging = stopCharging;
            this.SetMaxCurrent = setMaxCurrent;
        }

        /// <summary>
        /// Gets or Sets Information
        /// </summary>
        [DataMember(Name = "information", EmitDefaultValue = false)]
        public ChargerCapabilitiesInformation Information { get; set; }

        /// <summary>
        /// Gets or Sets ChargeState
        /// </summary>
        [DataMember(Name = "chargeState", EmitDefaultValue = false)]
        public ChargerCapabilitiesChargeState ChargeState { get; set; }

        /// <summary>
        /// Gets or Sets StartCharging
        /// </summary>
        [DataMember(Name = "startCharging", EmitDefaultValue = false)]
        public ChargerCapabilitiesStartCharging StartCharging { get; set; }

        /// <summary>
        /// Gets or Sets StopCharging
        /// </summary>
        [DataMember(Name = "stopCharging", EmitDefaultValue = false)]
        public ChargerCapabilitiesStopCharging StopCharging { get; set; }

        /// <summary>
        /// Gets or Sets SetMaxCurrent
        /// </summary>
        [DataMember(Name = "setMaxCurrent", EmitDefaultValue = false)]
        public ChargerCapabilitiesSetMaxCurrent SetMaxCurrent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChargerCapabilities {\n");
            sb.Append("  Information: ").Append(Information).Append("\n");
            sb.Append("  ChargeState: ").Append(ChargeState).Append("\n");
            sb.Append("  StartCharging: ").Append(StartCharging).Append("\n");
            sb.Append("  StopCharging: ").Append(StopCharging).Append("\n");
            sb.Append("  SetMaxCurrent: ").Append(SetMaxCurrent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ChargerCapabilities);
        }

        /// <summary>
        /// Returns true if ChargerCapabilities instances are equal
        /// </summary>
        /// <param name="input">Instance of ChargerCapabilities to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChargerCapabilities input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Information == input.Information ||
                    (this.Information != null &&
                    this.Information.Equals(input.Information))
                ) && 
                (
                    this.ChargeState == input.ChargeState ||
                    (this.ChargeState != null &&
                    this.ChargeState.Equals(input.ChargeState))
                ) && 
                (
                    this.StartCharging == input.StartCharging ||
                    (this.StartCharging != null &&
                    this.StartCharging.Equals(input.StartCharging))
                ) && 
                (
                    this.StopCharging == input.StopCharging ||
                    (this.StopCharging != null &&
                    this.StopCharging.Equals(input.StopCharging))
                ) && 
                (
                    this.SetMaxCurrent == input.SetMaxCurrent ||
                    (this.SetMaxCurrent != null &&
                    this.SetMaxCurrent.Equals(input.SetMaxCurrent))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Information != null)
                {
                    hashCode = (hashCode * 59) + this.Information.GetHashCode();
                }
                if (this.ChargeState != null)
                {
                    hashCode = (hashCode * 59) + this.ChargeState.GetHashCode();
                }
                if (this.StartCharging != null)
                {
                    hashCode = (hashCode * 59) + this.StartCharging.GetHashCode();
                }
                if (this.StopCharging != null)
                {
                    hashCode = (hashCode * 59) + this.StopCharging.GetHashCode();
                }
                if (this.SetMaxCurrent != null)
                {
                    hashCode = (hashCode * 59) + this.SetMaxCurrent.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
