/*
 * Enode API
 *
 * The Enode API is designed to make smart charging applications easy to develop. We provide an abstraction layer that reduces the complexity when extracting vehicle data and sending commands to vehicles from a variety of manufacturers.  The API has a RESTful architecture and utilizes OAuth2 authorization. 
 *
 * The version of the OpenAPI document: 1.17.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EnodeApi.Client.OpenAPIDateConverter;

namespace EnodeApi.Model
{
    /// <summary>
    /// ChargeScheduleStatus
    /// </summary>
    [DataContract(Name = "ChargeScheduleStatus")]
    public partial class ChargeScheduleStatus : IEquatable<ChargeScheduleStatus>, IValidatableObject
    {
        /// <summary>
        /// Defines ScheduleType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ScheduleTypeEnum
        {
            /// <summary>
            /// Enum CHARGE for value: CHARGE
            /// </summary>
            [EnumMember(Value = "CHARGE")]
            CHARGE = 1

        }


        /// <summary>
        /// Gets or Sets ScheduleType
        /// </summary>
        [DataMember(Name = "scheduleType", IsRequired = true, EmitDefaultValue = true)]
        public ScheduleTypeEnum ScheduleType { get; set; }
        /// <summary>
        /// An enum value that describes the current state of the Schedule
        /// </summary>
        /// <value>An enum value that describes the current state of the Schedule</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StateEnum
        {
            /// <summary>
            /// Enum ALIGNED for value: ALIGNED
            /// </summary>
            [EnumMember(Value = "ALIGNED")]
            ALIGNED = 1,

            /// <summary>
            /// Enum MISALIGNED for value: MISALIGNED
            /// </summary>
            [EnumMember(Value = "MISALIGNED")]
            MISALIGNED = 2,

            /// <summary>
            /// Enum PENDING for value: PENDING
            /// </summary>
            [EnumMember(Value = "PENDING")]
            PENDING = 3,

            /// <summary>
            /// Enum INACTIVEOVERRIDDEN for value: INACTIVE:OVERRIDDEN
            /// </summary>
            [EnumMember(Value = "INACTIVE:OVERRIDDEN")]
            INACTIVEOVERRIDDEN = 4,

            /// <summary>
            /// Enum INACTIVEDISABLED for value: INACTIVE:DISABLED
            /// </summary>
            [EnumMember(Value = "INACTIVE:DISABLED")]
            INACTIVEDISABLED = 5,

            /// <summary>
            /// Enum INACTIVEAWAY for value: INACTIVE:AWAY
            /// </summary>
            [EnumMember(Value = "INACTIVE:AWAY")]
            INACTIVEAWAY = 6,

            /// <summary>
            /// Enum INACTIVEINCAPABLE for value: INACTIVE:INCAPABLE
            /// </summary>
            [EnumMember(Value = "INACTIVE:INCAPABLE")]
            INACTIVEINCAPABLE = 7

        }


        /// <summary>
        /// An enum value that describes the current state of the Schedule
        /// </summary>
        /// <value>An enum value that describes the current state of the Schedule</value>
        [DataMember(Name = "state", IsRequired = true, EmitDefaultValue = true)]
        public StateEnum State { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ChargeScheduleStatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ChargeScheduleStatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ChargeScheduleStatus" /> class.
        /// </summary>
        /// <param name="scheduleId">scheduleId (required).</param>
        /// <param name="scheduleType">scheduleType (required).</param>
        /// <param name="changedAt">Time at which any value of the status last changed (required).</param>
        /// <param name="state">An enum value that describes the current state of the Schedule (required).</param>
        /// <param name="isCharging">Whether the target is currently actually charging (required).</param>
        /// <param name="isChargingExpected">Whether the target is currently expected to be charging (required).</param>
        /// <param name="isChargingExpectedParts">isChargingExpectedParts (required).</param>
        /// <param name="upcomingTransitions">List of upcoming transitions of the &#x60;shouldCharge&#x60; or &#x60;targetTemperature&#x60; value. A maximum of 2 items are returned. (required).</param>
        /// <param name="smartOverride">smartOverride (required).</param>
        /// <param name="externalStart">externalStart (required).</param>
        public ChargeScheduleStatus(Guid scheduleId = default(Guid), ScheduleTypeEnum scheduleType = default(ScheduleTypeEnum), DateTime changedAt = default(DateTime), StateEnum state = default(StateEnum), bool isCharging = default(bool), bool isChargingExpected = default(bool), ChargeScheduleStatusIsChargingExpectedParts isChargingExpectedParts = default(ChargeScheduleStatusIsChargingExpectedParts), List<ChargeScheduleStatusUpcomingTransitionsInner> upcomingTransitions = default(List<ChargeScheduleStatusUpcomingTransitionsInner>), SmartOverrideStatus smartOverride = default(SmartOverrideStatus), DEPRECATEDExternalStart externalStart = default(DEPRECATEDExternalStart))
        {
            this.ScheduleId = scheduleId;
            this.ScheduleType = scheduleType;
            this.ChangedAt = changedAt;
            this.State = state;
            this.IsCharging = isCharging;
            this.IsChargingExpected = isChargingExpected;
            // to ensure "isChargingExpectedParts" is required (not null)
            if (isChargingExpectedParts == null)
            {
                throw new ArgumentNullException("isChargingExpectedParts is a required property for ChargeScheduleStatus and cannot be null");
            }
            this.IsChargingExpectedParts = isChargingExpectedParts;
            // to ensure "upcomingTransitions" is required (not null)
            if (upcomingTransitions == null)
            {
                throw new ArgumentNullException("upcomingTransitions is a required property for ChargeScheduleStatus and cannot be null");
            }
            this.UpcomingTransitions = upcomingTransitions;
            // to ensure "smartOverride" is required (not null)
            if (smartOverride == null)
            {
                throw new ArgumentNullException("smartOverride is a required property for ChargeScheduleStatus and cannot be null");
            }
            this.SmartOverride = smartOverride;
            // to ensure "externalStart" is required (not null)
            if (externalStart == null)
            {
                throw new ArgumentNullException("externalStart is a required property for ChargeScheduleStatus and cannot be null");
            }
            this.ExternalStart = externalStart;
        }

        /// <summary>
        /// Gets or Sets ScheduleId
        /// </summary>
        [DataMember(Name = "scheduleId", IsRequired = true, EmitDefaultValue = true)]
        public Guid ScheduleId { get; set; }

        /// <summary>
        /// Time at which any value of the status last changed
        /// </summary>
        /// <value>Time at which any value of the status last changed</value>
        [DataMember(Name = "changedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime ChangedAt { get; set; }

        /// <summary>
        /// Whether the target is currently actually charging
        /// </summary>
        /// <value>Whether the target is currently actually charging</value>
        [DataMember(Name = "isCharging", IsRequired = true, EmitDefaultValue = true)]
        public bool IsCharging { get; set; }

        /// <summary>
        /// Whether the target is currently expected to be charging
        /// </summary>
        /// <value>Whether the target is currently expected to be charging</value>
        [DataMember(Name = "isChargingExpected", IsRequired = true, EmitDefaultValue = true)]
        public bool IsChargingExpected { get; set; }

        /// <summary>
        /// Gets or Sets IsChargingExpectedParts
        /// </summary>
        [DataMember(Name = "isChargingExpectedParts", IsRequired = true, EmitDefaultValue = true)]
        public ChargeScheduleStatusIsChargingExpectedParts IsChargingExpectedParts { get; set; }

        /// <summary>
        /// List of upcoming transitions of the &#x60;shouldCharge&#x60; or &#x60;targetTemperature&#x60; value. A maximum of 2 items are returned.
        /// </summary>
        /// <value>List of upcoming transitions of the &#x60;shouldCharge&#x60; or &#x60;targetTemperature&#x60; value. A maximum of 2 items are returned.</value>
        [DataMember(Name = "upcomingTransitions", IsRequired = true, EmitDefaultValue = true)]
        public List<ChargeScheduleStatusUpcomingTransitionsInner> UpcomingTransitions { get; set; }

        /// <summary>
        /// Gets or Sets SmartOverride
        /// </summary>
        [DataMember(Name = "smartOverride", IsRequired = true, EmitDefaultValue = true)]
        public SmartOverrideStatus SmartOverride { get; set; }

        /// <summary>
        /// Gets or Sets ExternalStart
        /// </summary>
        [DataMember(Name = "externalStart", IsRequired = true, EmitDefaultValue = true)]
        [Obsolete]
        public DEPRECATEDExternalStart ExternalStart { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChargeScheduleStatus {\n");
            sb.Append("  ScheduleId: ").Append(ScheduleId).Append("\n");
            sb.Append("  ScheduleType: ").Append(ScheduleType).Append("\n");
            sb.Append("  ChangedAt: ").Append(ChangedAt).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  IsCharging: ").Append(IsCharging).Append("\n");
            sb.Append("  IsChargingExpected: ").Append(IsChargingExpected).Append("\n");
            sb.Append("  IsChargingExpectedParts: ").Append(IsChargingExpectedParts).Append("\n");
            sb.Append("  UpcomingTransitions: ").Append(UpcomingTransitions).Append("\n");
            sb.Append("  SmartOverride: ").Append(SmartOverride).Append("\n");
            sb.Append("  ExternalStart: ").Append(ExternalStart).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ChargeScheduleStatus);
        }

        /// <summary>
        /// Returns true if ChargeScheduleStatus instances are equal
        /// </summary>
        /// <param name="input">Instance of ChargeScheduleStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChargeScheduleStatus input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ScheduleId == input.ScheduleId ||
                    (this.ScheduleId != null &&
                    this.ScheduleId.Equals(input.ScheduleId))
                ) && 
                (
                    this.ScheduleType == input.ScheduleType ||
                    this.ScheduleType.Equals(input.ScheduleType)
                ) && 
                (
                    this.ChangedAt == input.ChangedAt ||
                    (this.ChangedAt != null &&
                    this.ChangedAt.Equals(input.ChangedAt))
                ) && 
                (
                    this.State == input.State ||
                    this.State.Equals(input.State)
                ) && 
                (
                    this.IsCharging == input.IsCharging ||
                    this.IsCharging.Equals(input.IsCharging)
                ) && 
                (
                    this.IsChargingExpected == input.IsChargingExpected ||
                    this.IsChargingExpected.Equals(input.IsChargingExpected)
                ) && 
                (
                    this.IsChargingExpectedParts == input.IsChargingExpectedParts ||
                    (this.IsChargingExpectedParts != null &&
                    this.IsChargingExpectedParts.Equals(input.IsChargingExpectedParts))
                ) && 
                (
                    this.UpcomingTransitions == input.UpcomingTransitions ||
                    this.UpcomingTransitions != null &&
                    input.UpcomingTransitions != null &&
                    this.UpcomingTransitions.SequenceEqual(input.UpcomingTransitions)
                ) && 
                (
                    this.SmartOverride == input.SmartOverride ||
                    (this.SmartOverride != null &&
                    this.SmartOverride.Equals(input.SmartOverride))
                ) && 
                (
                    this.ExternalStart == input.ExternalStart ||
                    (this.ExternalStart != null &&
                    this.ExternalStart.Equals(input.ExternalStart))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ScheduleId != null)
                {
                    hashCode = (hashCode * 59) + this.ScheduleId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ScheduleType.GetHashCode();
                if (this.ChangedAt != null)
                {
                    hashCode = (hashCode * 59) + this.ChangedAt.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.State.GetHashCode();
                hashCode = (hashCode * 59) + this.IsCharging.GetHashCode();
                hashCode = (hashCode * 59) + this.IsChargingExpected.GetHashCode();
                if (this.IsChargingExpectedParts != null)
                {
                    hashCode = (hashCode * 59) + this.IsChargingExpectedParts.GetHashCode();
                }
                if (this.UpcomingTransitions != null)
                {
                    hashCode = (hashCode * 59) + this.UpcomingTransitions.GetHashCode();
                }
                if (this.SmartOverride != null)
                {
                    hashCode = (hashCode * 59) + this.SmartOverride.GetHashCode();
                }
                if (this.ExternalStart != null)
                {
                    hashCode = (hashCode * 59) + this.ExternalStart.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
