/*
 * Enode API
 *
 * The Enode API is designed to make smart charging applications easy to develop. We provide an abstraction layer that reduces the complexity when extracting vehicle data and sending commands to vehicles from a variety of manufacturers.  The API has a RESTful architecture and utilizes OAuth2 authorization. 
 *
 * The version of the OpenAPI document: 1.17.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EnodeApi.Client.OpenAPIDateConverter;

namespace EnodeApi.Model
{
    /// <summary>
    /// Defines getVehicles_field_parameter_oneOf
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum GetVehiclesFieldParameterOneOf
    {
        /// <summary>
        /// Enum ChargeState for value: chargeState
        /// </summary>
        [EnumMember(Value = "chargeState")]
        ChargeState = 1,

        /// <summary>
        /// Enum Location for value: location
        /// </summary>
        [EnumMember(Value = "location")]
        Location = 2,

        /// <summary>
        /// Enum Information for value: information
        /// </summary>
        [EnumMember(Value = "information")]
        Information = 3,

        /// <summary>
        /// Enum Odometer for value: odometer
        /// </summary>
        [EnumMember(Value = "odometer")]
        Odometer = 4,

        /// <summary>
        /// Enum Capabilities for value: capabilities
        /// </summary>
        [EnumMember(Value = "capabilities")]
        Capabilities = 5,

        /// <summary>
        /// Enum SmartChargingPolicy for value: smartChargingPolicy
        /// </summary>
        [EnumMember(Value = "smartChargingPolicy")]
        SmartChargingPolicy = 6

    }

}
