/*
 * Enode API
 *
 * The Enode API is designed to make smart charging applications easy to develop. We provide an abstraction layer that reduces the complexity when extracting vehicle data and sending commands to vehicles from a variety of manufacturers.  The API has a RESTful architecture and utilizes OAuth2 authorization. 
 *
 * The version of the OpenAPI document: 1.17.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EnodeApi.Client.OpenAPIDateConverter;

namespace EnodeApi.Model
{
    /// <summary>
    /// A range describing how close &#x60;heatSetpoint&#x60; and &#x60;coolSetpoint&#x60; can be. Only relevant in &#x60;AUTO&#x60; mode.
    /// </summary>
    [DataContract(Name = "HVAC_capabilities_setpointDifferenceRange")]
    public partial class HVACCapabilitiesSetpointDifferenceRange : IEquatable<HVACCapabilitiesSetpointDifferenceRange>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HVACCapabilitiesSetpointDifferenceRange" /> class.
        /// </summary>
        /// <param name="min">The minimum allowable temperature, inclusive..</param>
        /// <param name="max">The maximum allowable temperature, inclusive..</param>
        public HVACCapabilitiesSetpointDifferenceRange(decimal? min = default(decimal?), decimal? max = default(decimal?))
        {
            this.Min = min;
            this.Max = max;
        }

        /// <summary>
        /// The minimum allowable temperature, inclusive.
        /// </summary>
        /// <value>The minimum allowable temperature, inclusive.</value>
        [DataMember(Name = "min", EmitDefaultValue = true)]
        public decimal? Min { get; set; }

        /// <summary>
        /// The maximum allowable temperature, inclusive.
        /// </summary>
        /// <value>The maximum allowable temperature, inclusive.</value>
        [DataMember(Name = "max", EmitDefaultValue = true)]
        public decimal? Max { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HVACCapabilitiesSetpointDifferenceRange {\n");
            sb.Append("  Min: ").Append(Min).Append("\n");
            sb.Append("  Max: ").Append(Max).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HVACCapabilitiesSetpointDifferenceRange);
        }

        /// <summary>
        /// Returns true if HVACCapabilitiesSetpointDifferenceRange instances are equal
        /// </summary>
        /// <param name="input">Instance of HVACCapabilitiesSetpointDifferenceRange to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HVACCapabilitiesSetpointDifferenceRange input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Min == input.Min ||
                    (this.Min != null &&
                    this.Min.Equals(input.Min))
                ) && 
                (
                    this.Max == input.Max ||
                    (this.Max != null &&
                    this.Max.Equals(input.Max))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Min != null)
                {
                    hashCode = (hashCode * 59) + this.Min.GetHashCode();
                }
                if (this.Max != null)
                {
                    hashCode = (hashCode * 59) + this.Max.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
