/*
 * Enode API
 *
 * The Enode API is designed to make smart charging applications easy to develop. We provide an abstraction layer that reduces the complexity when extracting vehicle data and sending commands to vehicles from a variety of manufacturers.  The API has a RESTful architecture and utilizes OAuth2 authorization. 
 *
 * The version of the OpenAPI document: 1.17.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EnodeApi.Client.OpenAPIDateConverter;
using System.Reflection;

namespace EnodeApi.Model
{
    /// <summary>
    /// HVACSetPermanentHoldPayload
    /// </summary>
    [JsonConverter(typeof(HVACSetPermanentHoldPayloadJsonConverter))]
    [DataContract(Name = "HVACSetPermanentHoldPayload")]
    public partial class HVACSetPermanentHoldPayload : AbstractOpenAPISchema, IEquatable<HVACSetPermanentHoldPayload>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HVACSetPermanentHoldPayload" /> class
        /// with the <see cref="OFF" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of OFF.</param>
        public HVACSetPermanentHoldPayload(OFF actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HVACSetPermanentHoldPayload" /> class
        /// with the <see cref="AUTO" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of AUTO.</param>
        public HVACSetPermanentHoldPayload(AUTO actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HVACSetPermanentHoldPayload" /> class
        /// with the <see cref="HEAT" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of HEAT.</param>
        public HVACSetPermanentHoldPayload(HEAT actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HVACSetPermanentHoldPayload" /> class
        /// with the <see cref="COOL" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of COOL.</param>
        public HVACSetPermanentHoldPayload(COOL actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(AUTO))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(COOL))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(HEAT))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(OFF))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: AUTO, COOL, HEAT, OFF");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `OFF`. If the actual instance is not `OFF`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of OFF</returns>
        public OFF GetOFF()
        {
            return (OFF)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `AUTO`. If the actual instance is not `AUTO`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of AUTO</returns>
        public AUTO GetAUTO()
        {
            return (AUTO)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `HEAT`. If the actual instance is not `HEAT`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of HEAT</returns>
        public HEAT GetHEAT()
        {
            return (HEAT)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `COOL`. If the actual instance is not `COOL`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of COOL</returns>
        public COOL GetCOOL()
        {
            return (COOL)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HVACSetPermanentHoldPayload {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, HVACSetPermanentHoldPayload.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of HVACSetPermanentHoldPayload
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of HVACSetPermanentHoldPayload</returns>
        public static HVACSetPermanentHoldPayload FromJson(string jsonString)
        {
            HVACSetPermanentHoldPayload newHVACSetPermanentHoldPayload = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newHVACSetPermanentHoldPayload;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(AUTO).GetProperty("AdditionalProperties") == null)
                {
                    newHVACSetPermanentHoldPayload = new HVACSetPermanentHoldPayload(JsonConvert.DeserializeObject<AUTO>(jsonString, HVACSetPermanentHoldPayload.SerializerSettings));
                }
                else
                {
                    newHVACSetPermanentHoldPayload = new HVACSetPermanentHoldPayload(JsonConvert.DeserializeObject<AUTO>(jsonString, HVACSetPermanentHoldPayload.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("AUTO");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into AUTO: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(COOL).GetProperty("AdditionalProperties") == null)
                {
                    newHVACSetPermanentHoldPayload = new HVACSetPermanentHoldPayload(JsonConvert.DeserializeObject<COOL>(jsonString, HVACSetPermanentHoldPayload.SerializerSettings));
                }
                else
                {
                    newHVACSetPermanentHoldPayload = new HVACSetPermanentHoldPayload(JsonConvert.DeserializeObject<COOL>(jsonString, HVACSetPermanentHoldPayload.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("COOL");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into COOL: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(HEAT).GetProperty("AdditionalProperties") == null)
                {
                    newHVACSetPermanentHoldPayload = new HVACSetPermanentHoldPayload(JsonConvert.DeserializeObject<HEAT>(jsonString, HVACSetPermanentHoldPayload.SerializerSettings));
                }
                else
                {
                    newHVACSetPermanentHoldPayload = new HVACSetPermanentHoldPayload(JsonConvert.DeserializeObject<HEAT>(jsonString, HVACSetPermanentHoldPayload.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("HEAT");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into HEAT: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(OFF).GetProperty("AdditionalProperties") == null)
                {
                    newHVACSetPermanentHoldPayload = new HVACSetPermanentHoldPayload(JsonConvert.DeserializeObject<OFF>(jsonString, HVACSetPermanentHoldPayload.SerializerSettings));
                }
                else
                {
                    newHVACSetPermanentHoldPayload = new HVACSetPermanentHoldPayload(JsonConvert.DeserializeObject<OFF>(jsonString, HVACSetPermanentHoldPayload.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("OFF");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into OFF: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newHVACSetPermanentHoldPayload;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HVACSetPermanentHoldPayload);
        }

        /// <summary>
        /// Returns true if HVACSetPermanentHoldPayload instances are equal
        /// </summary>
        /// <param name="input">Instance of HVACSetPermanentHoldPayload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HVACSetPermanentHoldPayload input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for HVACSetPermanentHoldPayload
    /// </summary>
    public class HVACSetPermanentHoldPayloadJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(HVACSetPermanentHoldPayload).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return HVACSetPermanentHoldPayload.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
