/*
 * Enode API
 *
 * The Enode API is designed to make smart charging applications easy to develop. We provide an abstraction layer that reduces the complexity when extracting vehicle data and sending commands to vehicles from a variety of manufacturers.  The API has a RESTful architecture and utilizes OAuth2 authorization. 
 *
 * The version of the OpenAPI document: 1.17.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EnodeApi.Api;
using EnodeApi.Model;
using EnodeApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EnodeApi.Test.Model
{
    /// <summary>
    ///  Class for testing ChargeSchedule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChargeScheduleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChargeSchedule
        //private ChargeSchedule instance;

        public ChargeScheduleTests()
        {
            // TODO uncomment below to create an instance of ChargeSchedule
            //instance = new ChargeSchedule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChargeSchedule
        /// </summary>
        [Fact]
        public void ChargeScheduleInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChargeSchedule
            //Assert.IsType<ChargeSchedule>(instance);
        }


        /// <summary>
        /// Test the property 'HourMinute'
        /// </summary>
        [Fact]
        public void HourMinuteTest()
        {
            // TODO unit test for the property 'HourMinute'
        }
        /// <summary>
        /// Test the property 'FromTimestamp'
        /// </summary>
        [Fact]
        public void FromTimestampTest()
        {
            // TODO unit test for the property 'FromTimestamp'
        }
        /// <summary>
        /// Test the property 'ToTimestamp'
        /// </summary>
        [Fact]
        public void ToTimestampTest()
        {
            // TODO unit test for the property 'ToTimestamp'
        }
        /// <summary>
        /// Test the property 'Weekdays'
        /// </summary>
        [Fact]
        public void WeekdaysTest()
        {
            // TODO unit test for the property 'Weekdays'
        }
        /// <summary>
        /// Test the property 'ShouldCharge'
        /// </summary>
        [Fact]
        public void ShouldChargeTest()
        {
            // TODO unit test for the property 'ShouldCharge'
        }

    }

}
