/*
 * Enode API
 *
 * The Enode API is designed to make smart charging applications easy to develop. We provide an abstraction layer that reduces the complexity when extracting vehicle data and sending commands to vehicles from a variety of manufacturers.  The API has a RESTful architecture and utilizes OAuth2 authorization. 
 *
 * The version of the OpenAPI document: 1.17.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EnodeApi.Api;
using EnodeApi.Model;
using EnodeApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EnodeApi.Test.Model
{
    /// <summary>
    ///  Class for testing Consideration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsiderationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Consideration
        //private Consideration instance;

        public ConsiderationTests()
        {
            // TODO uncomment below to create an instance of Consideration
            //instance = new Consideration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Consideration
        /// </summary>
        [Fact]
        public void ConsiderationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Consideration
            //Assert.IsType<Consideration>(instance);
        }


        /// <summary>
        /// Test the property 'IsSmartChargeCapable'
        /// </summary>
        [Fact]
        public void IsSmartChargeCapableTest()
        {
            // TODO unit test for the property 'IsSmartChargeCapable'
        }
        /// <summary>
        /// Test the property 'IsPluggedIn'
        /// </summary>
        [Fact]
        public void IsPluggedInTest()
        {
            // TODO unit test for the property 'IsPluggedIn'
        }
        /// <summary>
        /// Test the property 'IsCharging'
        /// </summary>
        [Fact]
        public void IsChargingTest()
        {
            // TODO unit test for the property 'IsCharging'
        }
        /// <summary>
        /// Test the property 'RecentlyAtChargingLocation'
        /// </summary>
        [Fact]
        public void RecentlyAtChargingLocationTest()
        {
            // TODO unit test for the property 'RecentlyAtChargingLocation'
        }
        /// <summary>
        /// Test the property 'HasTimeEstimate'
        /// </summary>
        [Fact]
        public void HasTimeEstimateTest()
        {
            // TODO unit test for the property 'HasTimeEstimate'
        }
        /// <summary>
        /// Test the property 'NeedsSignificantCharge'
        /// </summary>
        [Fact]
        public void NeedsSignificantChargeTest()
        {
            // TODO unit test for the property 'NeedsSignificantCharge'
        }
        /// <summary>
        /// Test the property 'HasChargeAboveThreshold'
        /// </summary>
        [Fact]
        public void HasChargeAboveThresholdTest()
        {
            // TODO unit test for the property 'HasChargeAboveThreshold'
        }
        /// <summary>
        /// Test the property 'SingleUser'
        /// </summary>
        [Fact]
        public void SingleUserTest()
        {
            // TODO unit test for the property 'SingleUser'
        }
        /// <summary>
        /// Test the property 'WontStopExistingChargingSession'
        /// </summary>
        [Fact]
        public void WontStopExistingChargingSessionTest()
        {
            // TODO unit test for the property 'WontStopExistingChargingSession'
        }
        /// <summary>
        /// Test the property 'LikelyToGenerateSavings'
        /// </summary>
        [Fact]
        public void LikelyToGenerateSavingsTest()
        {
            // TODO unit test for the property 'LikelyToGenerateSavings'
        }

    }

}
