/*
 * Enode API
 *
 * The Enode API is designed to make smart charging applications easy to develop. We provide an abstraction layer that reduces the complexity when extracting vehicle data and sending commands to vehicles from a variety of manufacturers.  The API has a RESTful architecture and utilizes OAuth2 authorization. 
 *
 * The version of the OpenAPI document: 1.17.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EnodeApi.Api;
using EnodeApi.Model;
using EnodeApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EnodeApi.Test.Model
{
    /// <summary>
    ///  Class for testing VehicleSmartChargingStatusPlan
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VehicleSmartChargingStatusPlanTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VehicleSmartChargingStatusPlan
        //private VehicleSmartChargingStatusPlan instance;

        public VehicleSmartChargingStatusPlanTests()
        {
            // TODO uncomment below to create an instance of VehicleSmartChargingStatusPlan
            //instance = new VehicleSmartChargingStatusPlan();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VehicleSmartChargingStatusPlan
        /// </summary>
        [Fact]
        public void VehicleSmartChargingStatusPlanInstanceTest()
        {
            // TODO uncomment below to test "IsType" VehicleSmartChargingStatusPlan
            //Assert.IsType<VehicleSmartChargingStatusPlan>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ChargingLocationId'
        /// </summary>
        [Fact]
        public void ChargingLocationIdTest()
        {
            // TODO unit test for the property 'ChargingLocationId'
        }
        /// <summary>
        /// Test the property 'VehicleId'
        /// </summary>
        [Fact]
        public void VehicleIdTest()
        {
            // TODO unit test for the property 'VehicleId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Vendor'
        /// </summary>
        [Fact]
        public void VendorTest()
        {
            // TODO unit test for the property 'Vendor'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'NonSmartCost'
        /// </summary>
        [Fact]
        public void NonSmartCostTest()
        {
            // TODO unit test for the property 'NonSmartCost'
        }
        /// <summary>
        /// Test the property 'SmartCost'
        /// </summary>
        [Fact]
        public void SmartCostTest()
        {
            // TODO unit test for the property 'SmartCost'
        }
        /// <summary>
        /// Test the property 'StopAt'
        /// </summary>
        [Fact]
        public void StopAtTest()
        {
            // TODO unit test for the property 'StopAt'
        }
        /// <summary>
        /// Test the property 'StartAt'
        /// </summary>
        [Fact]
        public void StartAtTest()
        {
            // TODO unit test for the property 'StartAt'
        }
        /// <summary>
        /// Test the property 'EstimatedFinishAt'
        /// </summary>
        [Fact]
        public void EstimatedFinishAtTest()
        {
            // TODO unit test for the property 'EstimatedFinishAt'
        }
        /// <summary>
        /// Test the property 'StopConfirmedAt'
        /// </summary>
        [Fact]
        public void StopConfirmedAtTest()
        {
            // TODO unit test for the property 'StopConfirmedAt'
        }
        /// <summary>
        /// Test the property 'StartConfirmedAt'
        /// </summary>
        [Fact]
        public void StartConfirmedAtTest()
        {
            // TODO unit test for the property 'StartConfirmedAt'
        }
        /// <summary>
        /// Test the property 'EndedAt'
        /// </summary>
        [Fact]
        public void EndedAtTest()
        {
            // TODO unit test for the property 'EndedAt'
        }
        /// <summary>
        /// Test the property 'FinalState'
        /// </summary>
        [Fact]
        public void FinalStateTest()
        {
            // TODO unit test for the property 'FinalState'
        }
        /// <summary>
        /// Test the property 'FailureCondition'
        /// </summary>
        [Fact]
        public void FailureConditionTest()
        {
            // TODO unit test for the property 'FailureCondition'
        }
        /// <summary>
        /// Test the property 'ExternalStart'
        /// </summary>
        [Fact]
        public void ExternalStartTest()
        {
            // TODO unit test for the property 'ExternalStart'
        }

    }

}
