/*
 * Enode API
 *
 * The Enode API is designed to make smart charging applications easy to develop. We provide an abstraction layer that reduces the complexity when extracting vehicle data and sending commands to vehicles from a variety of manufacturers.  The API has a RESTful architecture and utilizes OAuth2 authorization. 
 *
 * The version of the OpenAPI document: 1.17.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EnodeApi.Api;
using EnodeApi.Model;
using EnodeApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EnodeApi.Test.Model
{
    /// <summary>
    ///  Class for testing VendorActionTargetState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VendorActionTargetStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VendorActionTargetState
        //private VendorActionTargetState instance;

        public VendorActionTargetStateTests()
        {
            // TODO uncomment below to create an instance of VendorActionTargetState
            //instance = new VendorActionTargetState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VendorActionTargetState
        /// </summary>
        [Fact]
        public void VendorActionTargetStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" VendorActionTargetState
            //Assert.IsType<VendorActionTargetState>(instance);
        }


        /// <summary>
        /// Test the property 'MaxCurrent'
        /// </summary>
        [Fact]
        public void MaxCurrentTest()
        {
            // TODO unit test for the property 'MaxCurrent'
        }
        /// <summary>
        /// Test the property 'Legacy'
        /// </summary>
        [Fact]
        public void LegacyTest()
        {
            // TODO unit test for the property 'Legacy'
        }

    }

}
